name: 'Build and Test'

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - uses: actions/checkout@v3
      - name: Restore cached dependencies
        id: dependency-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lockb') }}
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Save dependency cache
        id: dependency-save
        uses: actions/cache/save@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lockb') }}
      - name: Check formatting
        run: bun run check-format
      - name: Build
        run: bun run build
        # Upload repo with built files and dependencies for use in subsequent jobs
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - uses: actions/checkout@v3
      - name: Restore cached dependencies
        id: dependency-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lockb') }}
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Run unit tests
        run: bun run test
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - uses: actions/checkout@v3
      - name: Restore cached dependencies
        id: dependency-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lockb') }}
      - name: Start app
        run: bun start &
      - name: Restore Cypress cache
        id: cypress-restore
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('bun.lockb') }}
      - name: Install Cypress
        run: bun cypress install
      - name: Save Cypress cache
        id: cypress-save
        uses: actions/cache/save@v3
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('bun.lockb') }}
      - name: Run Cypress e2e
        run: bun cypress run --e2e --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
